# Generated by Django 2.0.5 on 2020-05-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chengji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bId', models.CharField(max_length=18)),
                ('bname', models.CharField(max_length=10)),
                ('bgoal', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
