# Generated by Django 3.0.1 on 2020-05-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chengji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chengji',
            name='btime',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chengji',
            name='bgoal',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
